### ISSUE TITLE
How to build and flash this project?

### ISSUE THREAD

**Issue by dodancs** [Gitshaoxiang/M5Unit-LoRa-E220-Chat#1]
Hey,
I've been exploring this project for a couple of hours and after many hours I managed to build and flash some version of the firmware, but the card computer does not boot it. At the end, after adding the required libs from git repos, I run `pio run -e m5stack-stamps3` from the commandline to produce a version of the firmware, supposedly for the target platform, then flashed it with esptool.py `esptool.py --baud 1500000 --port /dev/tty.usbmodem0 write_flash 0x0000 .pio/build/m5stack-stamps3/firmware.bin`, but still it does not work.

Can you please provide some documentation on how to properly build it?

Thanks!

**Comment by Gitshaoxiang** [comment]
Hello dude.  the firmware.bin is the app partition. it is not the whole firmware.  you also need to flash the bootloader and partition table.  suggest you use the vscode platformIO plugin to build and flash the firmware.
